### ISSUE TITLE
[QUESTION] May I ask what is `VIDEO_CODEC_ID`

### ISSUE THREAD

**Issue by donwyze** [awslabs/amazon-kinesis-video-streams-producer-c#245]
When I updated from v1.2.0 to the latest master, I encountered an error in compiling, saying `unknown type name ‘VIDEO_CODEC_ID’`

I grep the entire file without finding the definition

What do I need to do to ensure that the compilation passes ?

commit id : 6a7aab4fcde0791b5b092a15e61a5cacfc57c259

```
/amazon-kinesis-video-streams-producer-c/src/include/com/amazonaws/kinesis/video/cproducer/Include.h:540:89: error: unknown type name ‘VIDEO_CODEC_ID’; did you mean ‘MKV_AAC_CODEC_ID’?
  540 | PUBLIC_API STATUS createOfflineVideoStreamInfoProviderWithCodecs(PCHAR, UINT64, UINT64, VIDEO_CODEC_ID, PStreamInfo*);
      |                                                                                         ^~~~~~~~~~~~~~
      |                                                                                         MKV_AAC_CODEC_ID
/amazon-kinesis-video-streams-producer-c/src/include/com/amazonaws/kinesis/video/cproducer/Include.h:557:95: error: unknown type name ‘VIDEO_CODEC_ID’; did you mean ‘MKV_AAC_CODEC_ID’?
  557 | BLIC_API STATUS createRealtimeAudioVideoStreamInfoProviderWithCodecs(PCHAR, UINT64, UINT64, VIDEO_CODEC_ID, AUDIO_CODEC_ID, PStreamInfo*);
      |                                                                                             ^~~~~~~~~~~~~~
      |                                                                                             MKV_AAC_CODEC_ID

```

**Comment by hassanctech** [comment]
Yes you can use this one:  https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/29a2155a6fabded1570f8f967e054345d80c3c6d/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L560

The Producer C project depends on the PIC project, when you update you need to make sure you're also building the cmake dependences (commit hashes are specified and they should be up to date).
